#!/bin/bash
# 🤖 INSTALA PRE-COMMIT HOOK PARA VALIDAÇÃO CONTÍNUA
#
# Nível: ALÉM DO VALE DO SILÍCIO
#
# Este script instala um pre-commit hook que:
# 1. Detecta mudanças em scripts de análise
# 2. Re-valida métricas automaticamente
# 3. Bloqueia commits se drift > 5%
# 4. Atualiza documentação se --auto-update habilitado
#
# Usage:
#   ./scripts/phase5/install_validation_hook.sh
#   ./scripts/phase5/install_validation_hook.sh --auto-update

set -e

# Colors
GREEN='\033[92m'
RED='\033[91m'
BLUE='\033[94m'
BOLD='\033[1m'
RESET='\033[0m'

# Detect project root
if [ -d "cineprod-flask/.git" ]; then
    GIT_DIR="cineprod-flask/.git"
elif [ -d ".git" ]; then
    GIT_DIR=".git"
else
    echo -e "${RED}❌ Git repository not found${RESET}"
    exit 1
fi

HOOK_PATH="$GIT_DIR/hooks/pre-commit"
AUTO_UPDATE=""

if [ "$1" = "--auto-update" ]; then
    AUTO_UPDATE="--auto-update"
fi

echo -e "${BLUE}${BOLD}🤖 Installing Documentation Validation Hook${RESET}\n"

# Create pre-commit hook
cat > "$HOOK_PATH" << 'HOOK_EOF'
#!/bin/bash
# 🤖 PRE-COMMIT VALIDATION HOOK
# Auto-generated by install_validation_hook.sh

# Colors
GREEN='\033[92m'
RED='\033[91m'
YELLOW='\033[93m'
BLUE='\033[94m'
BOLD='\033[1m'
RESET='\033[0m'

echo -e "${BLUE}🤖 Running documentation validation...${RESET}"

# Detect if AI analysis scripts were modified
CHANGED_FILES=$(git diff --cached --name-only)
ANALYSIS_MODIFIED=0

if echo "$CHANGED_FILES" | grep -q "scripts/phase5/ai_"; then
    ANALYSIS_MODIFIED=1
    echo -e "${YELLOW}⚠️  AI analysis scripts modified - re-validating metrics${RESET}"
fi

# Detect if documentation was modified
DOC_MODIFIED=0
if echo "$CHANGED_FILES" | grep -q "docs/fase_5/"; then
    DOC_MODIFIED=1
fi

# Run validation if relevant files changed
if [ $ANALYSIS_MODIFIED -eq 1 ] || [ $DOC_MODIFIED -eq 1 ]; then
    # Find project root
    if [ -f "scripts/phase5/validate_documentation.py" ]; then
        PROJECT_ROOT="."
    elif [ -f "../scripts/phase5/validate_documentation.py" ]; then
        PROJECT_ROOT=".."
    else
        echo -e "${RED}❌ Cannot find validate_documentation.py${RESET}"
        exit 1
    fi

    # Run validation
    AUTO_UPDATE_FLAG=""
    if [ "$VALIDATE_DOCS_AUTO_UPDATE" = "1" ]; then
        AUTO_UPDATE_FLAG="--auto-update"
    fi

    if python3 "$PROJECT_ROOT/scripts/phase5/validate_documentation.py" $AUTO_UPDATE_FLAG; then
        echo -e "${GREEN}✅ Documentation validation PASSED${RESET}"

        # If auto-update was used, add updated files
        if [ -n "$AUTO_UPDATE_FLAG" ]; then
            echo -e "${BLUE}📝 Auto-updated documentation files staged${RESET}"
            git add docs/fase_5/*.md
        fi
    else
        echo -e "\n${RED}${BOLD}❌ COMMIT BLOCKED - Documentation validation FAILED${RESET}"
        echo -e "${YELLOW}Fix the issues above or run:${RESET}"
        echo -e "  python3 scripts/phase5/validate_documentation.py"
        echo -e "\n${YELLOW}To bypass (not recommended):${RESET}"
        echo -e "  git commit --no-verify"
        exit 1
    fi
else
    echo -e "${GREEN}✅ No validation needed (no AI/docs changes)${RESET}"
fi

exit 0
HOOK_EOF

# Make hook executable
chmod +x "$HOOK_PATH"

# Configure auto-update if requested
if [ -n "$AUTO_UPDATE" ]; then
    git config hooks.validatedocs.autoupdate true
    echo -e "${GREEN}✅ Auto-update ENABLED${RESET}"
else
    git config hooks.validatedocs.autoupdate false
    echo -e "${YELLOW}⚠️  Auto-update DISABLED (use --auto-update to enable)${RESET}"
fi

echo -e "\n${GREEN}${BOLD}✅ Pre-commit hook installed successfully!${RESET}\n"
echo -e "${BLUE}Hook path:${RESET} $HOOK_PATH"
echo -e "\n${BLUE}How it works:${RESET}"
echo -e "  • Detects changes to AI analysis scripts"
echo -e "  • Detects changes to Phase 5 documentation"
echo -e "  • Re-runs validation automatically"
echo -e "  • Blocks commits if metrics drift > 5%"

if [ -n "$AUTO_UPDATE" ]; then
    echo -e "  • ${GREEN}Auto-updates documentation on drift${RESET}"
fi

echo -e "\n${BLUE}Test it:${RESET}"
echo -e "  1. Edit docs/fase_5/README.md"
echo -e "  2. git add docs/fase_5/README.md"
echo -e "  3. git commit -m 'test: validation hook'"
echo -e "  4. Watch the validation run automatically ✨"

echo -e "\n${BLUE}Disable temporarily:${RESET}"
echo -e "  git commit --no-verify"

echo ""
