#!/bin/bash
# Complete Phase Workflow
# Valida conclusão de uma FASE e cria checkpoint

if [ -z "$1" ]; then
    echo "Usage: ./complete_phase.sh FASE_NAME"
    echo "Example: ./complete_phase.sh FASE2_COMPLETE"
    exit 1
fi

PHASE=$1

echo "🎯 SCRIPTUREMON - Completing Phase: $PHASE"
echo "========================================"
echo ""

# 1. Verificar se há mudanças não commitadas
echo "📊 Checking uncommitted changes..."
git status --short

if [ -n "$(git status --porcelain)" ]; then
    echo ""
    echo "⚠️  You have uncommitted changes!"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 2. Gerar summary desde último checkpoint
echo "📸 Generating phase summary..."
python3 scripts/git_session_summary.py --since "${PHASE}_START" 2>/dev/null || \
python3 scripts/git_session_summary.py --last 10

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 3. Extrair TODOs pendentes
echo "📝 Checking pending tasks..."
python3 scripts/extract_tasks_from_git.py --priority HIGH 2>&1 | head -30

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 4. Criar checkpoint
echo "💾 Creating checkpoint..."
CHECKPOINT_DIR="memory/checkpoints"
mkdir -p "$CHECKPOINT_DIR"

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
CHECKPOINT_FILE="$CHECKPOINT_DIR/${TIMESTAMP}_${PHASE}.md"

cat > "$CHECKPOINT_FILE" <<EOF
# CHECKPOINT: $PHASE

**Timestamp:** $(date '+%Y-%m-%d %H:%M:%S')
**Git Commit:** $(git rev-parse --short HEAD)

## Session Summary

$(python3 scripts/git_session_summary.py --last 5 2>/dev/null || echo "Git summary unavailable")

## Pending Tasks

$(python3 scripts/extract_tasks_from_git.py --priority HIGH --json 2>/dev/null | head -50 || echo "[]")

## Next Steps

- Review checkpoint: $CHECKPOINT_FILE
- Continue to next FASE
- Or close session

---
Auto-generated by complete_phase.sh
EOF

echo "✅ Checkpoint saved: $CHECKPOINT_FILE"
echo ""

# 5. Sugerir tag Git
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Suggested Git tag:"
echo "   git tag -a $PHASE -m \"Completed $PHASE\""
echo ""
read -p "Create tag now? (y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    git tag -a "$PHASE" -m "Completed $PHASE - Auto-tagged by workflow"
    echo "✅ Tag created: $PHASE"
fi

echo ""
echo "======================================"
echo "🎉 Phase $PHASE completed!"
echo "======================================"
echo ""
echo "Next: Start new phase or review work"
echo ""
