from __future__ import annotations
import os, time
from pathlib import Path
from typing import List
from .qscore import qscore as _qscore
from .character_analytics import character_analytics
from .charts_svg import bar_chart

def export_short(session, answer_text:str, ctx_text:str, ctx_cites:List[str], 
                 qscore_val:float|None, models:List[str]|None, weights:List[float]|None)->Path:
    home = Path(os.environ.get("SCRIPTUREMON_HOME","."))
    outdir = home/"reports"/"coverage"
    outdir.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d-%H%M%S")
    outpath = outdir/f"short_{ts}.md"
    # QScore fallback
    if qscore_val is None:
        qscore_val = _qscore(0.3,0.3,0.3,len(ctx_cites or []), len(answer_text or ""))
    # Doc text (se existir)
    doc = getattr(session,"active_doc",None)
    doc_name = Path(doc).name if doc else "—"
    raw = ""
    try:
        if doc and Path(doc).exists():
            raw = Path(doc).read_text(encoding="utf-8", errors="ignore")
    except Exception:
        raw = ""
    segments = getattr(session,"segments",[]) or []
    ana = character_analytics(raw, segments=segments, topk=8)
    # charts por ato (apenas top chars)
    svg_paths=[]
    if ana["act_counts"]:
        for act in (1,2,3):
            data=[]
            for c,_ in ana["top_chars"]:
                data.append((c[:8], float(ana["act_counts"][c].get(act,0))))
            svg = bar_chart(data, outdir/f"act{act}_{ts}.svg", width=420, height=120)
            svg_paths.append(svg.name)
    # mix table simples
    mix_tbl="_no model mix available_"
    if models and weights:
        rows=["| Model | Weight |","|---|---|"]+[f"| {m} | {w:.2f} |" for m,w in zip(models,weights)]
        mix_tbl="\n".join(rows)
    # pairs
    pairs_md = "\n".join([f"- **{a}** × **{b}** → {n}" for (a,b),n in ana["top_pairs"]]) or "_no pairs_"
    # top chars
    chars_md = "\n".join([f"- **{c}** — {n} cenas" for c,n in ana["top_chars"]]) or "_no characters_"
    # answer excerpt
    excerpt = "\n".join((answer_text or "").splitlines()[:8])
    md = f"""# Scripturemon — Short Editorial

**Documento:** {doc_name}  
**QScore:** {qscore_val:.1f}

## Model Mix
{mix_tbl}

## Top Characters
{chars_md}

## Top Pairs (scene co‑occurrence)
{pairs_md}

## Acts — Charts
{" ".join(f"![]({p})" for p in svg_paths) if svg_paths else "_no charts_"}

## Brutal Notes (excerpt)
{excerpt}

*Generated by Scripturemon — short one‑pager.*
"""
    outpath.write_text(md, encoding="utf-8")
    return outpath